In [24]:
import pandas as pd
from sqlalchemy import create_engine
import seaborn as sns
import matplotlib.pyplot as plt

database_name = 'telecom'
table_name= 'xdr_data'

connection_params = { "host": "localhost", "user": "postgres", "password": "00000000",
                    "port": "5432", "database": database_name}

engine = create_engine(f"postgresql+psycopg2://{connection_params['user']}:{connection_params['password']}@{connection_params['host']}:{connection_params['port']}/{connection_params['database']}")

# str or SQLAlchemy Selectable (select or text object)
sql_query = 'SELECT * FROM xdr_data '

df = pd.read_sql(sql_query, con= engine)

In [18]:
df

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      149429 non-null  object
 30  Handset Type                              149429 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

In [20]:
df.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,5.000000e+00,5.000000,5.000000,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,2.000000,2.0,5.000000,...,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00
mean,1.311448e+19,411.400000,609.000000,1.392207e+06,2.082013e+14,3.371152e+10,3.547207e+13,53.500000,5.0,19.000000,...,1.849503e+07,1.408443e+07,1.504887e+07,6.911990e+06,4.887325e+08,6.058002e+06,4.818181e+08,1.095858e+07,4.006016e+07,5.314478e+08
std,1.386163e+10,298.871712,280.862956,2.668021e+05,5.884296e+08,4.214225e+07,1.999601e+11,16.263456,0.0,15.716234,...,2.756649e+06,6.796098e+06,4.171594e+06,6.901172e+06,2.366720e+08,6.204045e+06,2.117728e+08,4.442369e+06,9.499696e+06,2.388042e+08
min,1.311448e+19,1.000000,171.000000,1.089009e+06,2.082003e+14,3.366496e+10,3.528151e+13,42.000000,5.0,6.000000,...,1.525938e+07,2.501332e+06,8.198936e+06,4.152180e+05,2.295846e+08,3.956300e+05,1.717444e+08,4.215763e+06,2.788364e+07,2.798073e+08
25%,1.311448e+19,235.000000,606.000000,1.321509e+06,2.082014e+14,3.368185e+10,3.535661e+13,47.750000,5.0,6.000000,...,1.585461e+07,1.469958e+07,1.399465e+07,1.097942e+06,2.780823e+08,1.170709e+06,4.106926e+08,8.814393e+06,3.674974e+07,3.088796e+08
50%,1.311448e+19,486.000000,652.000000,1.361762e+06,2.082014e+14,3.369980e+10,3.540701e+13,53.500000,5.0,16.000000,...,1.972566e+07,1.514664e+07,1.712458e+07,6.163408e+06,5.277072e+08,3.529801e+06,5.269042e+08,1.279728e+07,3.854281e+07,5.691386e+08
75%,1.311448e+19,565.000000,662.000000,1.365104e+06,2.082014e+14,3.375034e+10,3.552121e+13,59.250000,5.0,23.000000,...,2.024740e+07,1.896287e+07,1.758779e+07,9.656251e+06,6.087501e+08,1.084972e+07,5.507095e+08,1.391032e+07,4.332422e+07,6.533850e+08
max,1.311448e+19,770.000000,954.000000,1.823652e+06,2.082019e+14,3.376063e+10,3.579401e+13,65.000000,5.0,44.000000,...,2.138812e+07,1.911173e+07,1.833841e+07,1.722713e+07,7.995382e+08,1.434415e+07,7.490399e+08,1.505514e+07,5.380039e+07,8.460285e+08

In [21]:
df.isnull().sum()

Bearer Id                                   0
Start                                       0
Start ms                                    0
End                                         0
End ms                                      0
Dur. (ms)                                   0
IMSI                                        0
MSISDN/Number                               0
IMEI                                        0
Last Location Name                          0
Avg RTT DL (ms)                             3
Avg RTT UL (ms)                             3
Avg Bearer TP DL (kbps)                     0
Avg Bearer TP UL (kbps)                     0
TCP DL Retrans. Vol (Bytes)                 5
TCP UL Retrans. Vol (Bytes)                 5
DL TP < 50 Kbps (%)                         0
50 Kbps < DL TP < 250 Kbps (%)              0
250 Kbps < DL TP < 1 Mbps (%)               0
DL TP > 1 Mbps (%)                          0
UL TP < 10 Kbps (%)                         0
10 Kbps < UL TP < 50 Kbps (%)               0
50 Kbps < UL TP < 300 Kbps (%)              0
UL TP > 300 Kbps (%)                        0
HTTP DL (Bytes)                             5
HTTP UL (Bytes)                             5
Activity Duration DL (ms)                   0
Activity Duration UL (ms)                   0
Dur. (ms).1                                 0
Handset Manufacturer                        0
Handset Type                                0
Nb of sec with 125000B < Vol DL             5
Nb of sec with 1250B < Vol UL < 6250B       5
Nb of sec with 31250B < Vol DL < 125000B    5
Nb of sec with 37500B < Vol UL              5
Nb of sec with 6250B < Vol DL < 31250B      5
Nb of sec with 6250B < Vol UL < 37500B      5
Nb of sec with Vol DL < 6250B               0
Nb of sec with Vol UL < 1250B               0
Social Media DL (Bytes)                     0
Social Media UL (Bytes)                     0
Google DL (Bytes)                           0
Google UL (Bytes)                           0
Email DL (Bytes)                            0
Email UL (Bytes)                            0
Youtube DL (Bytes)                          0
Youtube UL (Bytes)                          0
Netflix DL (Bytes)                          0
Netflix UL (Bytes)                          0
Gaming DL (Bytes)                           0
Gaming UL (Bytes)                           0
Other DL (Bytes)                            0
Other UL (Bytes)                            0
Total UL (Bytes)                            0
Total DL (Bytes)                            0
dtype: int64

In [22]:
df.nunique()

Bearer Id                                   5
Start                                       5
Start ms                                    5
End                                         5
End ms                                      5
Dur. (ms)                                   5
IMSI                                        5
MSISDN/Number                               5
IMEI                                        5
Last Location Name                          5
Avg RTT DL (ms)                             2
Avg RTT UL (ms)                             1
Avg Bearer TP DL (kbps)                     4
Avg Bearer TP UL (kbps)                     3
TCP DL Retrans. Vol (Bytes)                 0
TCP UL Retrans. Vol (Bytes)                 0
DL TP < 50 Kbps (%)                         1
50 Kbps < DL TP < 250 Kbps (%)              1
250 Kbps < DL TP < 1 Mbps (%)               1
DL TP > 1 Mbps (%)                          1
UL TP < 10 Kbps (%)                         1
10 Kbps < UL TP < 50 Kbps (%)               1
50 Kbps < UL TP < 300 Kbps (%)              1
UL TP > 300 Kbps (%)                        1
HTTP DL (Bytes)                             0
HTTP UL (Bytes)                             0
Activity Duration DL (ms)                   4
Activity Duration UL (ms)                   4
Dur. (ms).1                                 5
Handset Manufacturer                        2
Handset Type                                5
Nb of sec with 125000B < Vol DL             0
Nb of sec with 1250B < Vol UL < 6250B       0
Nb of sec with 31250B < Vol DL < 125000B    0
Nb of sec with 37500B < Vol UL              0
Nb of sec with 6250B < Vol DL < 31250B      0
Nb of sec with 6250B < Vol UL < 37500B      0
Nb of sec with Vol DL < 6250B               5
Nb of sec with Vol UL < 1250B               5
Social Media DL (Bytes)                     5
Social Media UL (Bytes)                     5
Google DL (Bytes)                           5
Google UL (Bytes)                           5
Email DL (Bytes)                            5
Email UL (Bytes)                            5
Youtube DL (Bytes)                          5
Youtube UL (Bytes)                          5
Netflix DL (Bytes)                          5
Netflix UL (Bytes)                          5
Gaming DL (Bytes)                           5
Gaming UL (Bytes)                           5
Other DL (Bytes)                            5
Other UL (Bytes)                            5
Total UL (Bytes)                            5
Total DL (Bytes)                            5
dtype: int64

In [27]:
#Group the data by "Handset Type" and count the occurrences
handset_counts = df.groupby("Handset Type").size()

#Sort the counts in decending order
handset_counts_sorted = handset_counts.sort_values(ascending=False)

#Extract the top 10 handsets
top_10_handsets = handset_counts_sorted.head(10)

print("Top 10 Handsets Used by Customers:")
print(top_10_handsets)

Top 10 Handsets Used by Customers:
Handset Type
Huawei B528S-23A                19752
Apple iPhone 6S (A1688)          9419
Apple iPhone 6 (A1586)           9023
undefined                        8987
Apple iPhone 7 (A1778)           6326
Apple iPhone Se (A1723)          5187
Apple iPhone 8 (A1905)           4993
Apple iPhone Xr (A2105)          4568
Samsung Galaxy S8 (Sm-G950F)     4520
Apple iPhone X (A1901)           3813
dtype: int64

In [26]:
#group the data by Handset manufacturers
manufacturers_counts = df.groupby("Handset Manufacturer").size()

#Sort the counts in decending order
manufacturers_counts_sorted = manufacturers_counts.sort_values(ascending=False)

#Extract the top 3 manufacturers
top_3_manufacturers = manufacturers_counts_sorted.head(3)

print("Top 3 manufacturers:")
print(top_3_manufacturers)

Top 3 manufacturers:
Handset Manufacturer
Apple      59565
Samsung    40839
Huawei     34423
dtype: int64